
//for products
export const PRODUCT_LOAD ="PRODUCT_LOAD"
export const PRODUCT_SUCESS ="PRODUCT_SUCESS"
export const PRODUCT_FAIL ="PRODUCT_FAIL"
export const ADD_PRODUCT = "ADD_PRODUCT";
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";


//for user auth
export const USER_LOADING="USER_LOADING"
export const LOGIN_USER="LOGIN_USER"
export const REGISTER_USER="REGISTER_USER"
export const LOGOUT_USER="LOGOUT_USER"
export const GET_AUTH_USER="GET_AUTH_USER"
export const AUTH_ERROR="AUTH_ERROR"


//for cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";


//for orders(admin)
export const CART_EMPTY = "CART_EMPTY";
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDERS_LIST_REQUEST = "ORDERS_LIST_REQUEST";
export const ORDERS_LIST_SUCCESS = "ORDERS_LIST_SUCCESS";
export const ORDERS_LIST_FAIL = "ORDERS_LIST_FAIL";


//users (admin)
export const GET_USER_LOAD = "GET_USER_LOAD";
export const GET_USER = "GET_USER";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

